"""Alter Comment model

Revision ID: 3ecd94d90897
Revises: 1818f9d17176
Create Date: 2019-10-27 23:19:42.927494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecd94d90897'
down_revision = '1818f9d17176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'like_count')
    # ### end Alembic commands ###
